version: "3.8"
services:
  api:
    build: 
      context: .    
      dockerfile: Dockerfile.Api
    ports:
      - "8000:80"
    networks: 
      - proxy-net
    links:
      - mongo
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    restart: always
    networks: 
      - proxy-net
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"

networks: 
  proxy-net:
    external: 
      name: kafka_network  
