FROM mcr.microsoft.com/dotnet/sdk:7.0-alpine AS build
COPY . .
RUN dotnet restore *.sln
RUN dotnet publish -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:7.0-alpine
WORKDIR /app
COPY --from=build /app/publish .
EXPOSE 80
ENV ASPNETCORE_ENVIRONMENT=Development
ENTRYPOINT ["dotnet", "ScoreCalculator.Api.dll"]